### ISSUE TITLE
Colours may not take effect on navigate to build job

### ISSUE THREAD

**Issue by jeshan** [JoshuaJWilborn/colorize-the-logs#9]
1. In a new browser window, navigate to project, e.g `https://us-east-1.console.aws.amazon.com/codesuite/codebuild/projects/your-project/history?region=us-east-1`
2. Click link for a recent build run in the build history.

You will see colour codes like:
![image](https://user-images.githubusercontent.com/1020565/71202300-5d6beb00-22b5-11ea-9ba9-1f311aac7aac.png)

Workaround:
3. Refresh this page with Control-R
Colour codes are properly rendered as expected:
![image](https://user-images.githubusercontent.com/1020565/71202342-6f4d8e00-22b5-11ea-93a7-6f885bfc7ddd.png)

Browser: Brave (Chrome-based)

I saw this with either running or failed jobs.

**Comment by JoshuaJWilborn** [comment]
I have the fix and will publish tomorrow.  Thanks for reporting bugs!

**Comment by JoshuaJWilborn** [comment]
@jeshan this should be fixed now :)
